DROP TABLE IF EXISTS user_integrations CASCADE;
DROP TABLE IF EXISTS tg_worker_sessions CASCADE;
DROP TABLE IF EXISTS one_time_auth_codes CASCADE;
DROP TABLE IF EXISTS user_sessions CASCADE;
DROP TABLE IF EXISTS albums CASCADE;
DROP TABLE IF EXISTS settings CASCADE;
DROP TABLE IF EXISTS tracks CASCADE;
DROP TABLE IF EXISTS users CASCADE;
